### ISSUE TITLE
Question: what is hybris synchronizer?

### ISSUE THREAD

**Issue by paulvi** [eljoujat/eclipseimpexeditor#2]
On the screenshot ![](https://camo.githubusercontent.com/b0c06a064bf9dc783f17d6b6d2d609287231f915/687474703a2f2f656c6a6f756a61742e6769746875622e696f2f696d616765732f696d7065782f706572666572656e6365735f312e706e67)

there is Hybris Synchronizer. (Spelled Hybris Sychnronizer.  ) Where did it come from?

**Comment by eljoujat** [comment]
Hi,
Hybris synchroniser was another plugin that allow to synchronise locale hybris data base and media directory with integration server, to reduce the number of times doing update system or init .

**Comment by paulvi** [comment]
Is there possibility to open it to public / open source ?
