### ISSUE TITLE
SSL error connecting to Hybris

### ISSUE THREAD

**Issue by burbonov** [eljoujat/eclipseimpexeditor#25]
Hi,

I am trying to open impex file and get the following error:

!ENTRY impexeditor.core 4 4 2017-01-18 12:02:23.889
!MESSAGE Connection refused to http://localhost:9001
!STACK 0
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching localhost found

It looks that http call is redirected to https and plugin can not establish ssl connection.

Eclipse version:
Spring Tool Suite 
Version: 3.8.1.RELEASE
Build Id: 201607290850
Platform: Eclipse Neon (4.6)

Hybris version: 6.2.0

Plugin version: impexeditor.core_1.6.0

Thanks,
Evgeniy

**Comment by MarkusSchlautmann** [comment]
Same behaviour with hybris version 6.3.0 an impexeditor.core_1.6.0

**Comment by eljoujat** [comment]
Thanks for your support, 

Bug fixed , the plugin can now handle ssl connection,
